### ISSUE TITLE
No Compiler_Methode declaration

### ISSUE THREAD

**Issue by balzercomp** [vdelachaux/4DPop-Macros#10]
Hi Vincent,

is it correct that "Declaration..." doesn't create the compiler directives for the method anymore? For me it doesn't and I cannot find any setting for that.

Thanks

Gerald

**Comment by vdelachaux** [comment]
Hi Gerald,
it's a WIP, so I haven't done all the features.
I'm thinking of a better way to do it, maybe create these declarations directly in the Compiler_xxx methods.
If you have an idea, it will be welcome.
Regards

**Comment by vdelachaux** [comment]
Hi Gerald,
I've just released a new version that supports directives for the compiler again
Let me know how it goes.
Regards

**Comment by balzercomp** [comment]
Sorry, havn't seen it before. Will check asap.

**Comment by balzercomp** [comment]
Maybe I'm blind, but the version I just downloaded as Master doesn't do it. It's from June 26th.

**Comment by vdelachaux** [comment]
The 18R3 version is not updated, I wait for return of the users.
But you can use the v18 version: 4DPop.v18.zip<https://github.com/vdelachaux/4DPop/releases/download/18/4DPop.v18.zip> just keep the 4DPop.4dbase component

v i n c e n t    d e    l a c h a u x
----------------------------------------
Bee green - keep it on the screen


[cid:image0b4453.JPG@9d4bd273.4c888718]
Vincent de Lachaux
Développeur 4D Senior
Email : Vincent.deLachaux@4d.com<mailto:Vincent.deLachaux@4d.com>
Web :   www.4D.com<http://www.4D.com>

4D SAS
66 route de Sartrouville
Parc Les Erables - Batiment 4
78230 Le Pecq - France
Standard :      +33 1 30 53 92 00



On 28 Jul 2020, at 15:08, Gerald Balzer <notifications@github.com<mailto:notifications@github.com>> wrote:



Maybe I'm blind, but the version I just downloaded as Master doesn't do it.

**Comment by vdelachaux** [comment]
forget this response. Not the good thread.

v i n c e n t    d e    l a c h a u x
----------------------------------------
Bee green - keep it on the screen


[cid:imageded016.JPG@0dcc2739.49bc29f1]
Vincent de Lachaux
Développeur 4D Senior
Email : Vincent.deLachaux@4d.com<mailto:Vincent.deLachaux@4d.com>
Web :   www.4D.com<http://www.4D.com>

4D SAS
66 route de Sartrouville
Parc Les Erables - Batiment 4
78230 Le Pecq - France
Standard :      +33 1 30 53 92 00



On 28 Jul 2020, at 15:25, vincent.delachaux@4d.com<mailto:vincent.delachaux@4d.com> wrote:

The 18R3 version is not updated, I wait for return of the users.
But you can use the v18 version: 4DPop.v18.zip<https://github.com/vdelachaux/4DPop/releases/download/18/4DPop.v18.zip> just keep the 4DPop.4dbase component

v i n c e n t    d e    l a c h a u x
----------------------------------------
Bee green - keep it on the screen

On 28 Jul 2020, at 15:08, Gerald Balzer <notifications@github.com<mailto:notifications@github.com>> wrote:



Maybe I'm blind, but the version I just downloaded as Master doesn't do it.

**Comment by vdelachaux** [comment]
> Maybe I'm blind, but the version I just downloaded as Master doesn't do it. It's from June 26th.

You must download the from the enhance_declaration branch: https://github.com/vdelachaux/4DPop-Macros/tree/enhance_declaration/Build/Components/4DPop%20Macros.4dbase
